### ISSUE TITLE
Can I add gpu label,such as "GPU 0"?

### ISSUE THREAD

**Issue by JiangShanCode** [utkuozdemir/nvidia_gpu_exporter#61]
GPU-uuid is too complex to understand.Can I add gpu label,such as "GPU 0"?I installed it by docker.

**Comment by utkuozdemir** [comment]
The exporter itself doesn't support adding an additional label. But it's still doable.

It depends on where you need it - if you need it on Grafana dashboard, you can edit the dashboard itself.

If you need it on the metric itself (in prometheus), you need to look into the relabel configs - they allow you to manipulate any metric you need: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

In both cases, the exporter exposes a dummy metric called `nvidia_smi_gpu_info` that exposes additional info on the GPU as labels - you can use that metric as the "lookup table" to find name by id. See: https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/METRICS.md

**Comment by JiangShanCode** [comment]
OK,I get it.Thank you for your reply.

**Comment by utkuozdemir** [comment]
No problem, good luck :)

**Comment by garykuok** [comment]
Hello, after searching for lots of examples online, I still couldn't change the uuid name scraping to the hostname. The metrics returned seems are not proper json.

Say, for example I have the extra info:
`nvidia_smi_gpu_info{driver_model_current="[N/A]",driver_model_pending="[N/A]",driver_version="460.27.04",name="GeForce RTX 3090",uuid=<some_id>,vbios_version="94.02.42.00.9A"} `

I want to changed the scraping name list from UUID to the name of the GPU, so I have the config below:
```
relabel_configs:
            - source_labels: [__uuid__]
              regex: '.*(name=\".*\").*'
              replacement: '$1'
              target_label: name
```
This apparently does not work. What should I modify to fulfill my wish? Actually, there's an "instance" key from Grafana's web UI when querying, I wonder if it can even better to use the "instance" in the dropdown list instead of "name" (since machines could have the exact same type of GPU)?

Many thanks in advance.

Chon Kit

**Comment by KeithTt** [comment]
![图片](https://user-images.githubusercontent.com/15189954/223302375-5bc42f8f-bc90-4311-89b7-f07749459624.png)

I think it is impossible to distinguish the GPUs by the GPU variable. Is there a upgrading plan? @utkuozdemir

**Comment by utkuozdemir** [comment]
@KeithTt I don't have time to do it at the moment. Maybe I do it in the future. Of course, PRs are welcome.
